config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :uploads
  resources :notifications, except: [:create]
  resources :contacts, only: [:new, :create]
  resources :tags, only: [:new, :create, :destroy, :index]

  post 'notify(.:format)' => 'notifications#create', as: :notify
  post 'delete-notifications/:id' => 'notifications#delete_all', as: :delete_notices

  get 'about'			      => 'pages#about'
  get 'faq'	    	      => 'pages#faq'
  get 'watch'		       	=> 'pages#watch'
  patch 'watch'         => 'pages#watch'
  get 'safe'            => 'pages#safe'
  get 'contact_us'      => 'pages#contact_us'
  get 'unsubscribe'     => 'pages#unsubscribe'
  get 'change_password' => 'pages#change_password', as: :change_password

  post 'reset'          => 'pages#password_reset', as: :password_reset
  get 'pw-reset'        => 'pages#send_pw_reset', as: :pw_reset
  post 'new_pw_by_email'    => 'pages#new_pw_by_email'

  post 'remove_email' => 'pages#remove_email'

  post 'send_email'  => 'users#send_mass_email'

  get 'submit'    => 'uploads#new'
  patch 'uploads/:id/save' => 'uploads#save_upload', as: :save_upload

  get 'signup'		=> 'users#new'
  resources :users, except: [:new]

  get 'login'			=> 'sessions#new'
  post 'login' 	  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  patch '/users/:id/ban(.:format)' => 'users#ban', as: :ban
  patch '/users/:id/make-admin(.:format)' => 'users#make_admin', as: :make_admin
  get 'elist'     => 'users#elist'
  get 'download-emails' => 'users#email_download', as: :email_download

  get 'terms'             => 'uploads#terms'
  get 'privacy'           => 'uploads#privacy_policy'
  post 'add_tags'         => 'uploads#add_tags'
  post 'flowplayer_login' => 'uploads#flowplayer_login'

  post 'uploads/:id' => 'uploads#update'
  resources :comments

  post 'blogs/:id' => 'blogs#add_comment'

  resources :videos
  post 'videos/new' => 'videos#create'
  post 'videos/:id' => 'videos#add_comment'

  resources :reports
  post 'unflag' => 'reports#unflag'

  get 'premium' => 'videos#premium'

  get 'market'          => 'market#index'
  get 'orders'          => 'market#orders'
  post 'mark_fulfilled' => 'market#mark_fulfilled'

  get 'review'    => 'uploads#review'

  get 'logo'      => 'pages#logo'
  get 'countdown' => 'pages#countdown'
  
  root 'pages#home'

  get 'googlefe18980250372b0b.html' => 'pages#googlefe18980250372b0b.html'
  get 'robots.txt'                  => 'pages#robots.txt'
 
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :comments


  validates :title, presence: true, length: {minimum: 3}, uniqueness: true
	validates :user_id, presence: true
	validates :content, presence: true, length: {minimum: 10}
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	before_action :set_blog, only: [:edit, :update, :show, :destroy, :add_comment]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@blogs = Blog.paginate(page: params[:page], per_page: 3).order('id DESC')
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.user = current_user

		if @blog.save
			flash[:success] = "Blog has been created."
			redirect_to blogs_path
		else
			render :new
		end
	end

	def show
		flags(params[:id], "blog-comment")
	end 

	def edit
		if Blog.find(params[:id])
		else
			render '/public/404.html'
		end
	end

	def update
		if @blog.update(blog_params)
			flash[:success] = "The blog #{@blog.title} was successfully updated."
			redirect_to blog_path(@blog)
		else
			render :edit
		end
	end

	def add_comment
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.blog_id = @blog.id
		title = Blog.find(@comment.blog_id).title
		if @comment.save
			@blog.comments << @comment
			# mark_video :comment, @comment.user_id, title
			redirect_to blog_path(@blog)
		else
			flash[:danger] = "#{@comment.errors.full_messages}"
			render :show
		end
	end

	def destroy
		@comments = Comment.where(blog_id: @blog.id)
		@comments.each do |comment|
			@flags = Report.where(comment_id: comment.id)
			@flags.each {|f| f.destroy}
			comment.destroy
		end
		@blog.destroy
		flash[:danger] = "The blog \"#{@blog.title}\" was deleted."
		redirect_to blogs_path
	end

	

	private

		def blog_params
			params.require(:blog).permit(:title, :content)
		end

		def set_blog
			@blog = Blog.find(params[:id])
		end

		def comment_params
			params.require(:comment).permit(:title, :comment, :blog_id, :user_id)
		end

		def require_same_user
		if current_user != @blog.user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own blog"
			redirect_to root_path
		end		
	end

end

app/helpers/blog_helper.rb
module BlogHelper

	def remove_images(text)
	  text.gsub(/<img([^>])\S+/, "")
	end
end

app/views/blogs/_create.html.erb
<%= render 'layouts/errors', obj: @blog %>
<div class="container">
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@blog, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-1">
				
					<%= f.label :title %>
			</div>
			<div class="col-sm-12">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of blog", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-1">
				<%= f.label :content %>
			</div>
			<div class="col-sm-12">
				<%= f.text_area :content, class: "form-control tinymce", rows: "20", placeholder: "Body of blog" %>
				<%= tinymce %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: "btn btn-primary btn-lg" %>
			</div>
		</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			<div align="center">
				<h4 class="fix-link">[ <%= link_to "Cancel and return to Blogs.", blogs_path %> ]</h4>
			</div>
		</div>
	</div>
</div>
</div>
<%#= tinymce_assets %>
<!-- <script src="/assets/tinymce.js"></script> -->
<!--<script type="text/javascript">-->
<!--	$(document).on "page:receive", ->-->
<!--  	tinymce.remove()-->
<!--</script>-->

app/views/blogs/edit.html.erb
<div class="col-sm-8 col-sm-offset-2">
	<div class="alert alert-warning" role="alert">
		You are editing this blog post!
	</div>
</div>
<%= render 'create' %>

app/views/blogs/index.html.erb
 

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blog index 1 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
		</div>
		<div class="col-md-8 good-background">
			<div align="center">
				<h1>Blogs</h1>
			</div>
			<div class="col-sm-8">
				<% @blogs.each do |blog| %>
					<div class="fix-link blog-title">
						<h3><%= link_to blog.title, blog_path(blog) %></h3>
					</div>
					<div class="blog-body hide-img fix-link">
						<h4>
							<%= truncate(simple_format(blog.content, sanitize: false), length: 250, escape: false) %>
						</h4>  <!-- Escape: false stops html tags from showing up -->
						<div class="blog-meta-details">
							<h5><strong>Created By: <%= blog.user.username if blog.user %>,
								<%= time_ago_in_words(blog.created_at) %> ago.</strong> 
							</h5>
						</div>
					</div>

					<% if logged_in? && (current_user.admin || blog.user == current_user) %>
						<div class="blog-actions" align="right">
							<%= link_to "Edit this blog", edit_blog_path(blog),
									class: "btn btn-xs btn-primary" %>

							<%= link_to "Delete this blog", blog_path(blog),
									method: :delete, data: {confirm: "Are you sure you want to delete this blog?"}, class: "btn btn-xs btn-danger" %>
						</div>
					<% end %>
					<div class="comment-hr"></div>
				<% end %>
			</div>
			<div class="col-sm-4">
				<div align="center">
					
				</div>
			</div>
		</div>
		<div class="col-md-2">
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blog index 2 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
		</div>
	</div>
</div>

	
<div align="center">
	<%= will_paginate %>
</div>


<div align="center" class="responsive-ad">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- blog index 3 -->
	<ins class="adsbygoogle"
	     style="display:block"
	     data-ad-client="ca-pub-#"
	     data-ad-slot="#"
	     data-ad-format="auto"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>

app/views/blogs/new.html.erb
<%= render 'create' %>

app/views/blogs/show.html.erb
<% content_for :head do %>
	<meta property="og:url" content=<%= "http://mixed-messages.org/blogs/#{@blog.id}" %> />
	<meta property="og:type" content="blog" />
	<meta property="og:title" content="<%= @blog.title %>" />
	<meta property="og:image" content="http://mixed-messages.org/assets/stage.jpg" />
<% end %>

<% if logged_in? && current_user.admin %>
	<div align="center">
		<%= link_to "Edit this Blog", edit_blog_path(@blog), class: "btn btn-md btn-warning" %>
	</div>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-2">
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blog 1 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<!-- <script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script> -->
			</div>
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blog 4 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<!-- <script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script> -->
			</div>
		</div>
		<div class="col-sm-8">
			<div class="blog-body good-background">
				<h1 class="blog-title"><%= @blog.title.upcase %></h1>
				<div class="row">
					<div class="col-sm-6 col-xs-9">
						<h3 class="fix-link"><%= link_to @blog.user.username, user_path(@blog.user) %></h3>
						<h5>Created: <%= @blog.created_at.localtime.strftime("%B %d, %Y") %></h5>
					</div>
					<div class="share col-sm-6 col-xs-3">
						<div class="row">
							<div align="right">
								<div class="fb-share-button" data-href=<%= "http://mixed-messages.org/blogs/#{@blog.id}" %> data-layout="button" data-size="small" data-mobile-iframe="true">
									<a class="fb-xfbml-parse-ignore" target="_blank" href=<%="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fmixed-messages.org%2Fblogs%2F#{@blog.id}&amp;src=sdkpreparse" %> >Share</a>
								</div>
								<div>
									<a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Mixed-Messages&hashtags=mixedmessagesmovement">
										Tweet</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="comment-hr"></div>
				<div class="blog-content fix-link">
					<%= raw(@blog.content) %>
				</div>
				<div align="right">
					<%= link_to "Back to Top", "#top", class: "btn btn-md btn-primary" %>
				</div>
			</div>
			<div class="col-lg-2 col-lg-offset-5">
				<div align="center" style="margin-bottom: 20px;">
					<%= link_to "Return to blogs", blogs_path, class: "btn btn-md btn-primary" %>
				</div>
			</div>
		</div>
		<div class="col-sm-2">
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blog 2 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<!-- <script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script> -->
			</div>
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blog 5 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<!-- <script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script> -->
			</div>
		</div>
	</div>
</div>

<div align="center" class="responsive-ad">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- blog 3 -->
	<ins class="adsbygoogle"
	     style="display:block"
	     data-ad-client="ca-pub-#"
	     data-ad-slot="#"
	     data-ad-format="auto"></ins>
	<!-- <script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script> -->
</div>

<div class="container">
	<%= render 'layouts/comments', obj: @blog %>
</div>

<!-- Load Facebook SDK and twitter for JavaScript -->
<div id="fb-root"></div>
<script async>
 
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };
  return t;
}(document, "script", "twitter-wjs"));
</script>

<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	(adsbygoogle = window.adsbygoogle || []).push({});
	(adsbygoogle = window.adsbygoogle || []).push({});
	(adsbygoogle = window.adsbygoogle || []).push({});
	(adsbygoogle = window.adsbygoogle || []).push({});
</script>