config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :uploads
  resources :notifications, except: [:create]
  resources :contacts, only: [:new, :create]
  resources :tags, only: [:new, :create, :destroy, :index]

  post 'notify(.:format)' => 'notifications#create', as: :notify
  post 'delete-notifications/:id' => 'notifications#delete_all', as: :delete_notices

  get 'about'			      => 'pages#about'
  get 'faq'	    	      => 'pages#faq'
  get 'watch'		       	=> 'pages#watch'
  patch 'watch'         => 'pages#watch'
  get 'safe'            => 'pages#safe'
  get 'contact_us'      => 'pages#contact_us'
  get 'unsubscribe'     => 'pages#unsubscribe'
  get 'change_password' => 'pages#change_password', as: :change_password

  post 'reset'          => 'pages#password_reset', as: :password_reset
  get 'pw-reset'        => 'pages#send_pw_reset', as: :pw_reset
  post 'new_pw_by_email'    => 'pages#new_pw_by_email'

  post 'remove_email' => 'pages#remove_email'

  post 'send_email'  => 'users#send_mass_email'

  get 'submit'    => 'uploads#new'
  patch 'uploads/:id/save' => 'uploads#save_upload', as: :save_upload

  get 'signup'		=> 'users#new'
  resources :users, except: [:new]

  get 'login'			=> 'sessions#new'
  post 'login' 	  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  patch '/users/:id/ban(.:format)' => 'users#ban', as: :ban
  patch '/users/:id/make-admin(.:format)' => 'users#make_admin', as: :make_admin
  get 'elist'     => 'users#elist'
  get 'download-emails' => 'users#email_download', as: :email_download

  get 'terms'             => 'uploads#terms'
  get 'privacy'           => 'uploads#privacy_policy'
  post 'add_tags'         => 'uploads#add_tags'
  post 'flowplayer_login' => 'uploads#flowplayer_login'

  post 'uploads/:id' => 'uploads#update'
  resources :comments

  post 'blogs/:id' => 'blogs#add_comment'

  resources :videos
  post 'videos/new' => 'videos#create'
  post 'videos/:id' => 'videos#add_comment'

  resources :reports
  post 'unflag' => 'reports#unflag'

  get 'premium' => 'videos#premium'

  get 'market'          => 'market#index'
  get 'orders'          => 'market#orders'
  post 'mark_fulfilled' => 'market#mark_fulfilled'

  get 'review'    => 'uploads#review'

  get 'logo'      => 'pages#logo'
  get 'countdown' => 'pages#countdown'
  
  root 'pages#home'

  get 'googlefe18980250372b0b.html' => 'pages#googlefe18980250372b0b.html'
  get 'robots.txt'                  => 'pages#robots.txt'
 
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :uploads, dependent: :destroy 
	has_many :blogs
	has_many :notifications
	has_and_belongs_to_many :reports
	has_secure_password
	

	before_save {self.email = email.downcase}
	validates :username, presence: true, length: {minimum: 3, maximum: 40},
		uniqueness: {case_sensitive: false}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	
	validates :email, presence: true, length: {maximum: 105},
		uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}, on: :create

	validates :password, presence: true, length: {minimum: 6, maximum: 32}, on: :create
	validates :password_confirmation, presence: true, length: {minimum: 6, maximum: 32}, on: :create
	validates_confirmation_of :password

	validates :bio, length: { maximum: 3000}
  validates_acceptance_of :terms_and_conditions

	def self.search(search)
	  if search
	  	if Rails.env.development?
	  	  where(['username LIKE ?', "%#{search.downcase}%"])
	    else
	    	where(['username ILIKE ?', "%#{search.downcase}%"])
	    end
	  else
	    all
	  end
	end

	# def self.list
	# 	copy(["SELECT email FROM subscribes TO '/tmp/dump.csv' WITH CSV HEADER"])
	# end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show, :ban, :make_admin]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy, :ban, :make_admin, :index, :elist]

	def index
		@users = User.search(params[:search]).paginate(page: params[:page], per_page: 21)
	end

	def new
		if !logged_in?
			@user = User.new
		else
			flash[:success] = "You are already logged in."
			redirect_to root_path
		end
	end

	def create
		@user = User.new(user_params)

		# Add Recaptcha to signup
		# respond_to do |format|

			if verify_recaptcha(model: @user) && @user.save
				if @user.allow_emails
					Subscribe.create(email: @user.email)
				end
				Welcome.welcome(@user).deliver_now
				flash[:success] = "Welcome to Mixed-Messages, #{@user.username}!"
				session[:user_id] = @user.id
				redirect_to user_path(@user)
			else
				render 'new'
			end
	end
 
	def edit
	end 

	def update
		if @user.update(user_params)
			checkSub = Subscribe.where(email: @user.email)
			if @user.allow_emails && checkSub == nil
				Subscribe.create(email: @user.email)
			end
			flash[:success] = "Your account was successfully updated."
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end

	def show
		@user_uploads = @user.uploads.order("id DESC").paginate(page: params[:page], per_page: 6)
		@user_notes = @user.notifications.paginate(page: params[:page], per_page: 8)
	end

	def destroy 
		@user = User.find(params[:id])

		if @user.admin
			flash[:danger] = "You cannot delete another admin"
		else
			session[@user.id] = nil
			# Destroy notifications
			note = Notification.where(user_id: @user.id)
			if note != nil
				note.each {|x| x.destroy}
			end
			# Remove from mail list
			user_sub = Subscribe.where(email: @user.email)

			if !user_sub.empty?
				Subscribe.destroy(user_sub.first.id)
			end

			uname = @user.username
			@user.delete
			flash[:danger] = "User #{uname} has been deleted."
			redirect_to users_path
		end
	end

	def ban
		@user.toggle!(:banned)
		redirect_to users_path
	end

	def make_admin
		@user.toggle!(:admin)
		redirect_to users_path
	end

	def elist
		@users = Subscribe.all.paginate(page: params[:page], per_page: 21).order('id ASC')
		write_list @users
	end

	def send_mass_email
		@message = Hash.new
		Subscribe.all.each do |subscriber|
			@message = {email: subscriber.email,
									subject: send_email_params[:subject],
									content: send_email_params[:content]
								}
			EmailList.list(@message).deliver_later 
		end
		flash[:success] = "Email sent!"
		redirect_to :back
	end

	def email_download
		clear_list
		redirect_to root_path
	end


	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :zipcode, :bio, :password_confirmation, :allow_emails, :terms_and_conditions)
	end

	def set_user
		@user = User.find(params[:id])		
	end

	def require_same_user
		if logged_in? && current_user != @user && !current_user.admin?
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end		
	end

	def require_admin
		if !logged_in? or !current_user.admin?
			flash[:danger] = "Only admin users can perform that action"
			redirect_to root_path
		end
	end

	def send_email_params
		params.require(:send_email).permit(:subject, :content) 
	end

	def write_list users
		if logged_in? and current_user.admin? and Rails.env.production?
			File.open("tmp/emails.csv", "w") do |f|
				users.each do |user|
					f.puts user.email
				end
			end
		end
	end

	def clear_list
		if logged_in? and current_user.admin? and Rails.env.production?
			File.open("tmp/emails.csv", "w") do |f|
				f.puts " "
			end
		end
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'layouts/errors', obj: @user %> 
<div class="container good-background" style="padding-top: 30px;">
	<div align="center">
		<h1><%= logged_in? ? "Edit your account information" : "Sign up for Mixed Messages" %></h1><br/>
	</div>
	<div class="row">
	<div align="center">
		<div id="required"><strong>* Required</strong></div>
	</div>
		<div class="col-xs-12">
			<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
				<div class="form-group">
					<div class="control-label col-sm-2">
							<%= f.label "#{:username} *" %>
					</div>
					<div class="col-sm-8">
							<%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true, required: true %>
					</div>
				</div>

				<div class="form-group">
					<div class="control-label col-sm-2">
						<%= f.label "#{:email} *" %>
					</div>
					<div class="col-sm-8">
						<%= f.email_field :email, class: "form-control", placeholder: "Enter Email", required: true %>
					</div>
				</div>

				<% if !logged_in? %>
					<div class="form-group">
						<div class="control-label col-sm-2">
							<%= f.label "#{:password} *" %>
						</div>
						<div class="col-sm-8">
							<%= f.password_field :password, class: "form-control", placeholder: "Enter Password", required: true %>
						</div>
					</div>
					
					<div class="form-group">
						<div class="control-label col-sm-2">
							<%= f.label "#{:password_confirmation} *" %>
						</div>
						<div class="col-sm-8">
							<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter Password", required: true %>
						</div>
					</div>
				<% end %>
				<div class="form-group">
					<div class="control-label col-sm-2">
						<%= f.label :zipcode %>
					</div>
					<div class="col-sm-8" data-toggle="popover" data-trigger="focus" data-placement="left" data-content="Tagging a video with the zip code of where the subject resides, or at least where they were filmed, helps to increase the odds of someone recognizing them on the website. We believe that the greater the chance someone will be recognized on our site, the greater a deterrent the movement becomes. Please help us to sort our content and create the greatest incentive for people to pay attention to the road rather than their phones. You could save a life.">
						<%= f.text_field :zipcode, class: "form-control", placeholder: "Enter zipcode" %>
					</div>
				</div>
				<div class="form-group">
					<div class="control-label col-sm-2">
						<%= f.label :bio %>
					</div>
					<div class="col-sm-8">
						<%= f.text_area :bio, class: "form-control", rows: 5, placeholder: "Tell us something about you." %>
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-xs-12">
						<% if !logged_in? %>
							<div class="col-md-offset-2 col-md-3 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
								<div id="recaptcha">
									<%= recaptcha_tags %>
								</div>
							</div>
						<% end %>
						<div>
							<% if !logged_in? %>
								<div class="col-md-3 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1 tos fix-link">
									<%= f.check_box :terms_and_conditions, {checked: false, required: true } %> You agree to the <%= link_to "Terms and Conditions", terms_path, target: "_blank" %> and <%= link_to "Privacy Policy", privacy_path, target: "_blank" %>.
								</div>
								<div class="col-md-3 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1 tos">
									<%= f.check_box :allow_emails, {checked: true} %> Would you like to recieve email announcements?
								</div>
							<% end %>
						</div>
					</div>
					<% if logged_in? %>
							<div class="col-xs-12">
								<div align="center" class="fix-link">
									<h3><%= link_to "Change Password?", change_password_path %></h3>
								</div>
							</div>
					<% end %>
					<div class="col-sm-2 col-sm-offset-2 col-xs-5 col-xs-offset-1">
						<% if logged_in? %>
							<%= f.submit("Update Account", class: "btn btn-primary btn-lg") %>
						<% else %>
							<%= f.submit("Sign Up", class: "btn btn-primary btn-lg", id: "terms") %>
						<% end %>
					</div>
					<% if !logged_in? %>
						<div class="col-sm-2 col-xs-5" style="margin-left: 10px">
							<%= link_to "Log In!", login_path, class: "btn btn-lg btn-info" %>
						</div>
					<% end %>
					
				<% end %>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function () {
		$('[data-toggle="popover"]').popover()
})
</script>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/elist.html.erb
<h3 align="center">Users that allow emails</h3>
<h4 align="center"><%= pluralize(@users.count, "User").upcase %></h4>
<div align="center">
	
	<%= link_to "Download Email List", "/tmp/emails.csv", class: "btn btn-md btn-primary" %>
	<br/> 
	<%= link_to "Clear Email List", email_download_path, class: "btn btn-md btn-primary" %>
</div>
<% if @users.count > 100 %>
	<h1>You need to talk to Devjem before sending any emails</h1>
<% end %>
<div class="container">
	<div class="row">
		<div align="center">
			<%# will_paginate @users %>
			<% @users.each do |user| %>
				<ul class="user">
					<div class="well col-md-4">
						<li>
							<%= user.email.upcase %>
						</li>
					</div>
				</ul>
			<% end %>
		</div>
	</div>
	<div align="center">
		<%= will_paginate @users %>
	</div>

	<% if @users.count < 100 %>

		<%= form_for(:send_email, url: send_email_path, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-md-2">
					<% f.label :subject %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :subject, class: "form-control", placeholder: "Subject", autocomplete: false %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-md-2">
					<% f.label :content %>
				</div>
				<div class="col-md-8">
					<%= f.text_area :content, class: "form-control tinymce", rows: "20", placeholder: "Your Comment" %>
					<%= tinymce %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-md-offset-2">
					<%= f.submit "Send Email", class: "btn btn-primary btn-lg", data: {confirm: "Send Email?"} %>
				</div>
			</div>
		<% end %>
	<% end %>
</div> 
<!--<script type="text/javascript">-->
<!--	$(document).on "page:receive", ->-->
<!--  	tinymce.remove()-->
<!--</script>-->

app/views/users/index.html.erb
<h1 align="center">Mixed Messages Users</h1>
<h4 align="center"><%= pluralize(@users.count, "User").upcase %></h4>

<%= form_tag users_path, method: "get" do %>
	<div class="field" align="center" style="margin-bottom: 20px;">
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search Users", username: nil %>
	</div>
<% end %>
 

<div class="container">
	<div class="row">
		<div align="center">
			<%# will_paginate @users %>
			<% @users.each do |user| %>
				<ul class="listing">
					<div class="well col-md-4 clearfix">
						<li class="user clearfix">
							<%= link_to user.username.upcase, user_path(user) %>
						</li>
						<li><h4>Warn Level: <%= user.warn_level %></h4></li>
						<li><h6><%= user.email %></h6></li>
						<% if logged_in? && current_user.admin && !user.admin %>
							<li>
									<%= link_to "Make Administrator", make_admin_path(user), method: :patch, remote: :true, class: "btn btn-xs btn-info",
										data: {confirm: "Are you sure you want to make this user an Administrator?" }, rel: "nofollow" %>
								<% if !user.banned %>
										<%= link_to "Ban this user", ban_path(user), method: :patch, class: "btn btn-warning btn-xs",remote: :true, data: { confirm: "Are you sure you want to ban #{user.username}" }, rel: "nofollow" %>
								<% else %>
										<%= link_to "Un-Ban this user", ban_path(user), method: :patch, class: "btn btn-warning btn-xs", remote: :true, data: { confirm: "Are you sure you want to remove the ban on #{user.username}" }, rel: "nofollow" %>
								<% end %>
									<%= link_to "Delete User", user_path(user), method: :delete, class: "btn btn-xs btn-danger", data: {confirm: "Are you sure you want to delete this user?" }, rel: "nofollow" %>
							</li>
						<% end %>
					</div>
				</ul>
			<% end %>
		</div>
	</div>
	<div align="center">
		<%= will_paginate @users %>
	</div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div id="profile" class="container-fluid">
	<div class="row">
		<div class="col-sm-2">
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- User 1 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
		</div>

		<div class="col-sm-8 good-background">
			<div align="center">
				<% if logged_in? && current_user.admin && !@user.admin %>
					<%= link_to "Delete this user", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete #{@user.username}" }, class: "btn btn-danger btn-xl", rel: "nofollow" %>
					<% if !@user.banned && !@user.admin %>
						<%= link_to "Ban this user", ban_path(@user), method: :patch, remote: :true, data: { confirm: "Are you sure you want to ban #{@user.username}" }, class: "btn btn-warning btn-xl", rel: "nofollow" %>
					<% elsif !@user.admin %>
						<%= link_to "Un-Ban this user", ban_path(@user), method: :patch, remote: :true, data: { confirm: "Are you sure you want to remove the ban on #{@user.username}" }, class: "btn btn-warning btn-xl", rel: "nofollow" %>
					<% end %>
					<div align="center">
						<h3>Warn Level: <%= @user.warn_level %> </h3>
					</div>
				<% end %>
				<h1 class="section-title"><%= @user.username.upcase %></h1>
			</div>
			<!-- Left side -->		
			<div class="col-sm-7">	
				<div id="info">
					<div>
						<h3>Member since:</h3>
						<h4><%= @user.created_at.localtime.strftime("%B %d, %Y") %></h4><br/>
					</div>
					<% if logged_in? and (current_user == @user or current_user.admin?) %>
						<div>
							<h3>info:</h3>
							<% if @user.zipcode %>
								
								<h4><span class="glyphicon glyphicon-globe"></span> Zipcode: <%= @user.zipcode %></h4>
							<% elsif logged_in? && current_user == @user %>
								<h4 class="fix-link">
									<span class="glyphicon glyphicon-globe"></span>
									<%= link_to "Add a zipcode", edit_user_path(@user) %>
								</h4>
							<% end %>
						</div>
					<% end %>
					<% if logged_in? && current_user == @user %>
						<div>
							<h4 class="fix-link">
								<span class="glyphicon glyphicon-pencil"></span>
								<%= link_to "Edit your info", edit_user_path(@user) %>
							</h4>
						</div>
					<% end %>
					<br/>
				</div>
				<div id="bio" class="col-sm-12">
					<div>
						<% if @user.bio && !@user.bio.empty? %>
							<div>
								<h3>Bio:</h3>
							</div>
							<h4><%= @user.bio %></h4>
						<% elsif logged_in? && (current_user.admin || current_user == @user) %><br/>
							<h4 class="fix-link">
								<%= link_to "Edit your Bio", edit_user_path(@user) %>
							</h4>
						<% end %>
					</div>
				</div>
			</div>

			<!-- Right Side -->
			<% @delete_notice = Array.new %>
			<!-- User Notifications -->
			<div id="user-notifications" class="col-sm-5 col-sm-offset-0 col-xs-10 col-xs-offset-1">
				<% if logged_in? && !@user_notes.empty? && @user == current_user %>

					<!-- Delete all button -->
					<div align="center">
						<% @user_notes.each do |notice| %>
							<% @delete_notice.push(notice) %>
						<% end %>
						<%= link_to "Delete all notifications", delete_notices_path(@delete_notice), method: :post, class: "btn btn-sm btn-info", rel: "nofollow" %>
					</div>

					<!-- The list -->
					<ul class="list-group">
						<% @user_notes.each do |notice| %>
							<% if notice.notice_type == "success" %>
								<li class="list-group-item list-group-item-success">
									<%= link_to "X", notification_path(notice), method: :delete, class: "btn btn-xs btn-success", rel: "nofollow" %>
									<%= notice.notice %>
								</li>
							<% elsif notice.notice_type == "warning" %>
								<li class="list-group-item list-group-item-warning">
									<%= link_to "X", notification_path(notice), method: :delete, class: "btn btn-xs btn-warning", rel: "nofollow" %>
									<%= notice.notice %>
								</li>
							<% elsif notice.notice_type == "danger" %>
								<li class="list-group-item list-group-item-danger">
									<%= link_to "X", notification_path(notice), method: :delete, class: "btn btn-xs btn-danger", rel: "nofollow" %>
									<%= notice.notice %>
								</li>
							<% elsif notice.notice_type == "info" %>
								<li class="list-group-item list-group-item-info">
									<%= link_to "X", notification_path(notice), method: :delete, class: "btn btn-xs btn-info", rel: "nofollow" %>
									<%= notice.notice %>
								</li>
							<% end %>
						<% end %>
						<div align="center">
							<%= will_paginate (@user_notes) %>
						</div>
					</ul>
				<% end %>
			</div>
			<div class="col-xs-12">
				<div class="responsive-ad">
					<div align="center">
						<h6>Advertisement</h6>
						<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
						<!-- User 3 -->
						<ins class="adsbygoogle"
						     style="display:block"
						     data-ad-client="#"
						     data-ad-slot="#"
						     data-ad-format="auto"></ins>
						<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
						</script>
					</div>
				</div>
			</div>

			<!-- User Uploads -->
			<% if !@user_uploads.empty? %>
				<div class="col-xs-12">
					<div align="center">
						<h3><strong><%= @user_uploads.count %> Uploads by <%= @user.username.upcase %>:</strong></h3>
						<% @user_uploads.each do |upload| %>
							<% if (logged_in? && (current_user.admin || current_user == @user)) || upload.save_upload %>
								<div class="col-lg-4 col-sm-6 style-upload-index">
									<div align="center" class="single-upload">
										<% if upload.save_upload %>
											<div class="greentext">
												This video is available.
											</div>
										<% else %>
											<div class="redtext">
												This video has not yet been approved.
											</div>
										<% end %>
										<br/>
										<%= link_to (image_tag upload.file.thumb, height: "150px"), upload_path(upload) %>
										<br/>
										<h4><%= upload.title.upcase %></h4><br/> 
										<%= truncate(upload.note, length: 100) %><br/>
										<%= time_ago_in_words(upload.created_at) %><br/>
									</div>
								</div>
							<% end %>
						<% end %>
						<%= will_paginate @user_uploads %>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-sm-2">
			<div class="responsive-ad">
				<div align="center">
					<h6>Advertisement</h6>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- User 2 -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="#"
				     data-ad-slot="#"
				     data-ad-format="auto"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
		</div>
	</div>
</div>

<div align="center" class="responsive-ad">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- User 4 -->
	<ins class="adsbygoogle"
	     style="display:block"
	     data-ad-client="#"
	     data-ad-slot="#"
	     data-ad-format="auto"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>