config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :uploads
  resources :notifications, except: [:create]
  resources :contacts, only: [:new, :create]
  resources :tags, only: [:new, :create, :destroy, :index]

  post 'notify(.:format)' => 'notifications#create', as: :notify
  post 'delete-notifications/:id' => 'notifications#delete_all', as: :delete_notices

  get 'about'			      => 'pages#about'
  get 'faq'	    	      => 'pages#faq'
  get 'watch'		       	=> 'pages#watch'
  patch 'watch'         => 'pages#watch'
  get 'safe'            => 'pages#safe'
  get 'contact_us'      => 'pages#contact_us'
  get 'unsubscribe'     => 'pages#unsubscribe'
  get 'change_password' => 'pages#change_password', as: :change_password

  post 'reset'          => 'pages#password_reset', as: :password_reset
  get 'pw-reset'        => 'pages#send_pw_reset', as: :pw_reset
  post 'new_pw_by_email'    => 'pages#new_pw_by_email'

  post 'remove_email' => 'pages#remove_email'

  post 'send_email'  => 'users#send_mass_email'

  get 'submit'    => 'uploads#new'
  patch 'uploads/:id/save' => 'uploads#save_upload', as: :save_upload

  get 'signup'		=> 'users#new'
  resources :users, except: [:new]

  get 'login'			=> 'sessions#new'
  post 'login' 	  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  patch '/users/:id/ban(.:format)' => 'users#ban', as: :ban
  patch '/users/:id/make-admin(.:format)' => 'users#make_admin', as: :make_admin
  get 'elist'     => 'users#elist'
  get 'download-emails' => 'users#email_download', as: :email_download

  get 'terms'             => 'uploads#terms'
  get 'privacy'           => 'uploads#privacy_policy'
  post 'add_tags'         => 'uploads#add_tags'
  post 'flowplayer_login' => 'uploads#flowplayer_login'

  post 'uploads/:id' => 'uploads#update'
  resources :comments

  post 'blogs/:id' => 'blogs#add_comment'

  resources :videos
  post 'videos/new' => 'videos#create'
  post 'videos/:id' => 'videos#add_comment'

  resources :reports
  post 'unflag' => 'reports#unflag'

  get 'premium' => 'videos#premium'

  get 'market'          => 'market#index'
  get 'orders'          => 'market#orders'
  post 'mark_fulfilled' => 'market#mark_fulfilled'

  get 'review'    => 'uploads#review'

  get 'logo'      => 'pages#logo'
  get 'countdown' => 'pages#countdown'
  
  root 'pages#home'

  get 'googlefe18980250372b0b.html' => 'pages#googlefe18980250372b0b.html'
  get 'robots.txt'                  => 'pages#robots.txt'
 
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	include ActiveModel::Validations
	include Rails.application.routes.url_helpers

  belongs_to :user
  has_and_belongs_to_many :comments
  has_and_belongs_to_many :tags


  before_save do
  	if self.zipcode.nil?
  		self.zipcode = "0"
  	end
  end

  validates :title, presence: true, length: {minimum: 3, maximum: 100}, uniqueness: true
	validates :user_id, presence: true, on: :create
	#validates :note, presence: true, length: {minimum: 10, maximum: 1000}

	## mount_uploader :file, FileUploader
  # process_in_background :file, :thumb#, ThumbWorker

	validates :file, presence: true, on: :create
	validates :file, file_size: {less_than: 100.megabytes}

  validates_acceptance_of :upload_terms_and_conditions


	def self.search(search, zip)
		if zip
			where(['cast(zipcode as text) LIKE ?', "%#{zip}%"])
	  elsif search
	  	self.joins("INNER JOIN tags_uploads ON uploads.id = tags_uploads.upload_id").where [ "tag_id = ?", search]
	  else
	    all
	  end
	end

	def to_jq_upload
    { "name" => read_attribute(:file),
    "size" => file.size,
    "url" => file.url,
    "thumbnail_url" => file.thumb.url,
    "delete_url" => upload_path(:id => id),
    "delete_type" => "DELETE" }
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
	before_action :set_upload, only: [:show, :edit, :update, :save_upload, :destroy]
	before_action :require_admin, only: [:review, :save_upload]
	#before_action :require_user, only: [:new]
 
	def index
		#@uploads = Upload.where(save_upload: true).order("id DESC")
		@uploads = Upload.search(params[:search], params[:zip]).paginate(page: params[:page], per_page: 9).where(save_upload: true).order("id DESC")
		
		@tags = Tag.all
	end

	def review
		@uploads = Upload.paginate(page: params[:page], per_page: 21).where(save_upload: false).order("id ASC")

	end
 
	def show
		flags(params[:id], "upload-comment")
		@tags = Tag.all
	end

	def new 
		@upload = Upload.new
		# @uploader = Upload.new.file
		# @uploader.success_action_redirect = upload_path(@upload)
	end

	def create

		@upload = Upload.new(upload_params)
		@upload.user = current_user

		if @upload.valid?
			@upload.thumb = "thumb_#{upload_params[:file].to_s.chomp(File.extname(upload_params[:file].to_s))}.jpg"
			@upload.save
			
			flash[:success] = "Your upload has been submitted. You will be notified if it is accepted."
			redirect_to upload_path(@upload)
		else
			render :new
		end
	end

	def edit
	end

	def update 
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.upload_id = @upload.id

		if @comment.save
			@upload.comments << @comment
			upload_title = Upload.find(@comment.upload_id).title
			mark_video :comment, @upload.user_id, upload_title, "member", @upload.id
		else
			flash[:danger] = "Did not work. #{@comment.errors.full_messages}"
			render :show
		end
	end

	def save_upload
		@upload.toggle!(:save_upload)
		if @upload.save_upload
			mark_video :success, @upload.user_id, @upload.title, "admin"
		else
			mark_video :denied, @upload.user_id, @upload.title, "admin" 
		end
	end


	def destroy
		mark_video :denied, @upload.user_id, @upload.title, "admin"
		@upload.remove_file!
		@upload.save
		@comments = Comment.where(upload_id: @upload.id)
		@comments.each do |comment|
			@flags = Report.where(comment_id: comment.id)
			@flags.each {|f| f.destroy}
			comment.destroy
		end
		@upload.destroy
		flash[:info] = "The upload #{@upload.title} has been deleted."
	end

	def upload_report
		#@comment = Comment.find
	end

	def add_tags
		@temp = add_tags_params[:tags]
		@temp.pop
		@upload = Upload.find(add_tags_params[:upload_id])
		puts "Tags: #{@tags}"
		@upload.update tags: Tag.find(@temp)
		redirect_to :back
	end

	def flowplayer_login
		request = format.json{username = flowplayer_login_params[:username],
			password = flowplayer_login_params[:password]}
		post "https://drive.api.flowplayer.org/login" 

	end


	private
		def upload_params
			params.require(:upload).permit(:title, :note, :zipcode, :file, :thumb, :upload_terms_and_conditions, @original_filename)
		end

		def add_tags_params
			params.require(:add_tags).permit(:upload_id, tags: [])
		end

		def comment_params
			params.require(:comment).permit(:title, :comment, :upload_id, :user_id)
		end

		def set_upload
			@upload = Upload.find(params[:id])
		end

		def require_admin
			if !logged_in? || !current_user.admin 
				flash[:danger] = "Administrator access required for that action"
				redirect_to '403.html'
			end
		end

		def require_user
			if !logged_in?
				redirect_to root_path
				flash[:warning] = "You must be logged in to do that."
			end
		end

		def flowplayer_login_params
			params.require(:flowplayer_login).permit(:username, :password)
		end


end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_submission_list.html.erb
<div>	
	<% @uploads.each do |upload| %>
		<div class="col-lg-4 col-sm-6 style-upload-index">
			<div align="center" class="single-upload">
				<% user = "Submitted by: #{upload.user.username}" %>
				<h4 class="fix-link"><%= link_to user, user_path(upload.user.id) %></h4><br/> 
				<% if Rails.env.development? %>
					<%= "File is: #{upload.file.thumb}" %><br/>
				<% end %>
					<%= link_to (image_tag upload.file.thumb, height: "150px"), upload_path(upload) %>
				<br/>
				<h4><%= upload.title %></h4><br/> 
				<%= truncate(upload.note, length: 100) %><br/>
				<%= time_ago_in_words(upload.created_at) %><br/>
				<% if logged_in? && current_user.admin %>
					<%= link_to "Delete", upload_path(upload), method: :delete, class: "btn btn-sm btn-info", data: {confirm: "Delete this submission?"} %>
					<% if !upload.save_upload %>
						<%= link_to "Allow", save_upload_path(upload), class: "btn btn-danger btn-sm", method: :patch, data: {confirm: "Allow this submission?"} %>
					<% else %>
						<%= link_to "Deny", save_upload_path(upload), class: "btn btn-warning btn-sm", method: :patch, data: {confirm: "Deny this submission but keep the file?"} %>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>
 

app/views/uploads/_submit_form.html.erb
<% content_for :head do |head| %>

<% end %>

<% if logged_in? %>
	<div class="col-lg-12">
		<div align="center">
			<h3>Submit your content here!</h3>
		</div>
	</div>


	<%= form_for(@upload, :html => {class: "form-horizontal", role: "form", enctype: "multipart/form-data", id: "fileupload"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				
					<%= f.label :title %>
			</div>
			<div class="col-sm-8">
					<%= f.text_field :title, class: "form-control", placeholder: "Title", required: true %>
			</div>
		</div>

		<div class="form-group">
			<div class="control-label col-sm-2">
					<%= f.label :zipcode %> 
			</div>

			<div class="col-sm-8" data-toggle="popover" data-trigger="focus" data-placement="left" data-content="Tagging a video with the zip code of where the subject resides, or at least where they were filmed, helps to increase the odds of someone recognizing them on the website. We believe that the greater the chance someone will be recognized on our site, the greater a deterrent the movement becomes. Please help us to sort our content and create the greatest incentive for people to pay attention to the road rather than their phones. You could save a life.">
					<%= f.text_field :zipcode, class: "form-control", placeholder: "Zipcode", value: current_user.zipcode %>
			</div>
		</div>
		
		<div class="form-group">
			<div class="control-label col-sm-2">
				
					<%= f.label :note %>
			</div>
			<div class="col-sm-8">
					<%= f.text_area :note, class: "form-control", rows: 10, placeholder: "Tell us about this video"%>
			</div>
		</div>
		 
		<div class="form-group">
			<div class="control-label col-sm-2">
				
					<%= f.label "#{:file} (<100mb)" %>
			</div>
			<div class="col-sm-5">
					<%= f.file_field :file, required: true %>
			</div>

			<div class="col-sm-8 tos">
				<%= f.check_box :upload_terms_and_conditions, {checked: false, required: true, id: "tos" } %> You agree to the <%= link_to "Terms and Conditions", terms_path, target: "_blank" %> and <%= link_to "Privacy Policy", privacy_path, target: "_blank" %>.
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-2">
				<%= f.submit( "Submit", class: "btn btn-primary btn-lg start", id: "submit-upload", onclick: "showDiv()", data: {confirm: "This might take a couple minutes. Please wait."} ) %>
			</div>

			<!-- Upload Progress Bar -->
<!-- 			<div class="col-sm-offset-1 col-sm-5">
				<div class="fileupload-loading"></div>
				<div id="bar" class="progress progress-success progress-striped active hidden">
				    <div class="progress-bar" style="width:0%;" role="progressbar"></div>
				</div>
			</div> -->
		</div>
	<% end %>

	<div id="loading-gif" style="display: none;">
		<div align="center">
			<%= image_tag "loading.gif" %><br/><h3>Loading</h3>
		</div>
	</div>

<% else %>

	<!-- Prompt for log in -->
	<div class="col-lg-8 col-lg-offset-2">
		<div align="center">
			<h3 class="fix-link"><%= link_to raw("Log in to submit<br/>your own!"), login_path, rel: "nofollow" %></h3>
		</div>
	</div>
<% end %>



<!-- ********************************** -->


<!-- Popup for Zipcode info -->

<script>
// document.getElementById('submit-upload').onclick=document.getElementById('loading-gif').style.display = "block";

	function showDiv() {
		document.getElementById('loading-gif').style.display = "block";
	}
	
	$(document).ready(function() {
		$(function () {
			$('[data-toggle="popover"]').popover();
		});
	});

</script>

app/views/uploads/index.html.erb
<div class="container-fluid">
	<div class="col-md-2 col-md-offset-0 col-xs-6 col-xs-offset-3">
		<ul class="tags">
			<li>
				<!-- Zipcode search -->
				<%= form_tag uploads_path, method: "get", rel: "nofollow" do %>
					<div class="field" align="center" style="margin-bottom: 20px;">
					<%= hidden_field_tag :search, params[:search] %>
					<%= text_field_tag :zip, "", id: "zipcode-search"%>
					<%= submit_tag "Zipcode", username: nil, class: "btn btn-sm btn-primary", id: "zipcode-search-btn" %>
					</div>
				<% end %>
			</li>

			<!-- Tags List -->
			<% if !@tags.nil? and !@tags.empty? %>
				
				<li><%= link_to "All Tags", uploads_path, class: "btn btn-sm btn-primary", rel: "nofollow" %></li>
				<% @tags.each do |tag| %>
					<%= form_tag uploads_path, method: "get", rel: "nofollow" do %>
						<%= hidden_field_tag :search, tag.id %>

						<li><%= submit_tag tag.tag_name, tags: nil, class: "btn btn-sm btn-primary" %></li>
					<% end %>
				<% end %>
			<% end %>
		</ul>

		<div class="responsive-ad">
			<div align="center">
				<h6>Advertisement</h6>
			</div>
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- Sub List 1 -->
			<ins class="adsbygoogle"
			     style="display:block"
			     data-ad-client="ca-pub-#"
			     data-ad-slot="#"
			     data-ad-format="auto"></ins>
			<!-- <script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script> -->
		</div>

	</div>
	<div class="col-md-8 col-md-offset-0 col-xs-12">
		<div class="row good-background">
			<div align="center">
				<h1>User Submissions</h1><br/>

				<%= will_paginate %>

			</div>

			<% if @uploads.empty? %>
				<div align="center" class="fix-link">
					<h3>No submissions yet!<br/><br/><%= link_to "Submit one yourself!", submit_path %></h3>
				</div>
			<% end %>
			<%= render 'submission_list', obj: @uploads %>


			<div align="center">
				<%= will_paginate %>
			</div>
		</div>
	</div>
	<div class="col-md-2">
		<div class="responsive-ad">
			<div align="center">
				<h6>Advertisement</h6>
			</div>
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- Sub List 2 -->
			<ins class="adsbygoogle"
			     style="display:block"
			     data-ad-client="ca-pub-#"
			     data-ad-slot="#"
			     data-ad-format="auto"></ins>
			<!-- <script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script> -->
		</div>
	</div>
</div>
<div class="responsive-ad">
	<div align="center">
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- Sub List 3 -->
		<ins class="adsbygoogle"
		     style="display:block"
		     data-ad-client="ca-pub-#"
		     data-ad-slot="#"
		     data-ad-format="auto"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		(adsbygoogle = window.adsbygoogle || []).push({});
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
</div>

app/views/uploads/new.html.erb
<%= render 'layouts/errors', obj: @upload %>   

<div class="container-fluid"> 
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 good-background">
			<div class="section-title">
				<h1 align="center">Get involved!</h1><br/><br/>
			</div>
			<div class="row">
				<div class="col-xs-10">
					<div class="lobster">“Against the assault of laughter, nothing can stand.  You are always fussing and fighting with your other weapons.  Do you ever use that one?  No; you leave it lying and rusting.  As a race, do you ever use it at all?  No; you lack the sense and the courage.”<br/> - <span class="underline">Mark Twain</span>
					</div>
				</div><br/><br/>
			</div>
			<div class="row">
				<div class="visible-xs col-xs-10 col-xs-offset-1">
					<div class="embed-responsive embed-responsive-16by9 submit-video">
						<iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/F45sKajeNq4?rel=0" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
				<div class="col-md-4 faq involved-text">
					&nbsp;&nbsp;&nbsp;&nbsp;
					Here’s your chance to do something good without having to do anything great!  If you are tired of seeing smart phone zombies half-heartedly manipulating the controls of their rolling death carriages, this is your chance to fight back.  The threat of death and damage may not convince people to wait until later to play on their phones, but we have noticed that catching them on camera does.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;

					Helping is simple.  Drive wherever you normally would drive, and don’t change your routine.  Just make a conscious effort to keep an eye on the drivers around you in traffic.  If you notice someone endangering others because they are not paying attention to the road, try to catch them on camera.<br/><br/><br/><div class="comment-hr hidden-xs hidden-sm"></div>  
				</div>
				<div class="col-md-8 col-md-offset-0 col-xs-10 col-xs-offset-1">
					<div class="submit-video hidden-xs embed-responsive embed-responsive-16by9">
						<iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/F45sKajeNq4?rel=0" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="submit-space visible-md visible-xs">
						<%= render 'submit_form' %>
					</div>

				</div>
			</div>
			<div class="row">
				<div class="col-lg-7 faq involved-text fix-link">&nbsp;&nbsp;&nbsp;&nbsp;
					<strong>**DO NOT attempt to drive your car and film the other person . . . </strong>you do not help the situation by becoming as much or more of a danger than the person you are trying to film**  <%= link_to "Check out our video on safe filming techniques,", safe_path %> and <%= link_to "read our blog", blogs_path %> for ideas and instructions for how to get quality footage and create good submission material.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;

					Once you have obtained a clip of a distracted driver, just submit it here on the website along with the zip code where it was filmed, and any jokes or comments you would make about the video.  We will review the submissions and post the clips to the website so that everyone they know can see them (and hopefully convince them to change their ways . . . ).<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;

					You can also put other drivers on notice to keep focused by ordering a Mixed-Messages bumper sticker.  The sticker is an inexpensive way to remind drivers near you in traffic that you are paying attention, and if they are not, they may receive the celebrity treatment!  That little extra incentive could be the difference that convinces someone to be responsible.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;

					It is our hope that when enough people have joined in the movement, the number of cameras and bumper stickers on the road will convince drivers everywhere to pay attention to their surroundings, rather than worrying about whatever message or social media update they have coming in at the time.  So join in, help us, and have some fun with a car pool buddy.  You never know whose life you may save by shaming someone into waiting until they are parked to check their phone!<br/><br/><br/>
				</div>
				<div class="submit-space col-lg-5 hidden-md hidden-xs">
					<%= render 'submit_form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/uploads/review.html.erb
<div class="container">
	<div class="row good-background">

		<% if @uploads.empty? %>
				<div align="center" class="move-bottom">
					<h1>no uploads TO REVIEW</h1>
				</div>
			</div>

		<% else %>
			<div align="center">
				<h1>Videos in Que: <%= @uploads.count %></h1><br/>
				<%= form_for :flowplayer_login, url: flowplayer_login_path do |f| %>
					<%= f.hidden_field :username, value: "#" %>
					<%= f.hidden_field :password, value: "#" %>
					<%= f.submit "Log In To Flowplayer", class: "btn btn-lg btn-primary" %>
				<% end %>
				<%# button_tag "Log in to Flowplayer", class: "btn btn-lg btn-primary", id: "fp-login" %>
			</div>
			<%= render 'submission_list', obj: @uploads %>
			<div align="center">
				<%= will_paginate %>
			</div>
		<% end %>
	</div>
</div>

app/views/uploads/show.html.erb
<% content_for :head do %>
	<!-- <script src="mediaelement.js"></script> -->
	<link rel="stylesheet" href="http://releases.flowplayer.org/7.0.2/skin/skin.css">
	<script src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
	<script src="http://releases.flowplayer.org/7.0.2/flowplayer.min.js"></script>
<% end %> 


<%= render 'layouts/errors', obj: @upload %>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<div align="center">
				<h1 class="fix-link"><%= link_to @upload.user.username, user_path(@upload.user) %></h1><br/>
			</div>
		</div>
		<div align="center">
			<div class="col-xs-12 col-md-6 col-md-offset-3">
				<div class="upload-video">
					<div align="center">
						<% if Rails.env.development? %>
							<%= "File is: #{@upload.file}" %><br/>							
						<% end %>

						<!-- Media Player -->
						<!-- 	
						<%# if Rails.env.development? %>
							<%# "File is: #{@upload.file}" %><br/>							
						<%# end %>
						<%# video_tag @upload.file, controls: true, autobuffer: true, class: "mejs__player", id: "player", height: "350px", preload: "auto" %>
						<br/> --> 

						<!-- Flowplayer -->
						<div class="player fp-edgy">
							<%= video_tag @upload.file, height: "300px", type: "video/mp4" %>
							<br/>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="hidden-sm hidden-xs col-md-3">
			<!-- Tag system -->
			<% if logged_in? and current_user.admin? %>
				<div align="left">
					<%= form_for :add_tags, url: add_tags_path do |f| %>
						<div class="field">
							<%= f.hidden_field :upload_id, value: @upload.id %>
							<%= f.collection_check_boxes :tags, Tag.all, :id, :tag_name do |tag| %>
								<%= tag.check_box %>
								<%= tag.label %><br/>
							<% end %>
						</div>
						<%= f.submit "Mark Tags", class: "btn btn-sm btn-primary" %>
					<% end %>
				</div>
			<% end %>
		</div>

		<!-- Allow or deny the file -->
			<div class="col-md-4 col-xs-6">
				<% if logged_in? && current_user.admin %>
					<% if !@upload.save_upload %>
						<div align="right">
								<%= link_to "Allow File", save_upload_path(@upload), class: "btn btn-danger btn-lg", method: :patch, rel: "nofollow" %>
						</div>
					<% else %>
						<div align="right">
								<%= link_to "Deny File", save_upload_path(@upload), class: "btn btn-warning btn-lg", method: :patch, rel: "nofollow" %>
						</div>
					<% end %>
				<% end %>
			</div>

			<!-- Completely delete the file -->
			<div class="col-md-4 col-md-push-4 col-xs-6">
				<% if logged_in? && current_user.admin %>
					<div align="left">
							<%= link_to "Delete File", upload_path(@upload), method: :delete, class: "btn btn-info btn-lg", rel: "nofollow" %>
					</div>
				<% end %>
			</div>

			<!-- File info and tags -->
			<div class="col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2 upload-info">
				<div align="center">
					<h4><strong><%= @upload.title %></strong></h4><br/>
					<%= @upload.note %><br/>
					<%= time_ago_in_words(@upload.created_at).capitalize %> ago.<br/>
					<% if !@upload.tags.nil? %>
						<% @upload.tags.each do |tag| %>
							<div class="col-sm-3 btn btn-sm btn-primary upload-tags">
								<%= tag.tag_name %>
							</div>
						<% end %>
					<% end %>
				</div>	
			</div>
	</div>

	<% if @upload.save_upload %>
		<div class="container">
			<%= render 'layouts/comments', obj: @upload %>
		</div>
	<% end %>
</div>


<!-- <script>
// normal JavaScript 
var player;

(function() {
	player = new MediaElementPlayer('#player');
})();

window.onunload = function removePlayer() {
	if (!player.paused) {
		player.pause();
	}
	player.remove();
}
</script> -->

<script>

	$(document).ready(function() {
		$('.player').flowplayer();
	});

</script>