config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :uploads
  resources :notifications, except: [:create]
  resources :contacts, only: [:new, :create]
  resources :tags, only: [:new, :create, :destroy, :index]

  post 'notify(.:format)' => 'notifications#create', as: :notify
  post 'delete-notifications/:id' => 'notifications#delete_all', as: :delete_notices

  get 'about'			      => 'pages#about'
  get 'faq'	    	      => 'pages#faq'
  get 'watch'		       	=> 'pages#watch'
  patch 'watch'         => 'pages#watch'
  get 'safe'            => 'pages#safe'
  get 'contact_us'      => 'pages#contact_us'
  get 'unsubscribe'     => 'pages#unsubscribe'
  get 'change_password' => 'pages#change_password', as: :change_password

  post 'reset'          => 'pages#password_reset', as: :password_reset
  get 'pw-reset'        => 'pages#send_pw_reset', as: :pw_reset
  post 'new_pw_by_email'    => 'pages#new_pw_by_email'

  post 'remove_email' => 'pages#remove_email'

  post 'send_email'  => 'users#send_mass_email'

  get 'submit'    => 'uploads#new'
  patch 'uploads/:id/save' => 'uploads#save_upload', as: :save_upload

  get 'signup'		=> 'users#new'
  resources :users, except: [:new]

  get 'login'			=> 'sessions#new'
  post 'login' 	  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  patch '/users/:id/ban(.:format)' => 'users#ban', as: :ban
  patch '/users/:id/make-admin(.:format)' => 'users#make_admin', as: :make_admin
  get 'elist'     => 'users#elist'
  get 'download-emails' => 'users#email_download', as: :email_download

  get 'terms'             => 'uploads#terms'
  get 'privacy'           => 'uploads#privacy_policy'
  post 'add_tags'         => 'uploads#add_tags'
  post 'flowplayer_login' => 'uploads#flowplayer_login'

  post 'uploads/:id' => 'uploads#update'
  resources :comments

  post 'blogs/:id' => 'blogs#add_comment'

  resources :videos
  post 'videos/new' => 'videos#create'
  post 'videos/:id' => 'videos#add_comment'

  resources :reports
  post 'unflag' => 'reports#unflag'

  get 'premium' => 'videos#premium'

  get 'market'          => 'market#index'
  get 'orders'          => 'market#orders'
  post 'mark_fulfilled' => 'market#mark_fulfilled'

  get 'review'    => 'uploads#review'

  get 'logo'      => 'pages#logo'
  get 'countdown' => 'pages#countdown'
  
  root 'pages#home'

  get 'googlefe18980250372b0b.html' => 'pages#googlefe18980250372b0b.html'
  get 'robots.txt'                  => 'pages#robots.txt'
 
end

app/models/report.rb
class Report < ActiveRecord::Base
	has_and_belongs_to_many :users

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	before_action :require_admin, only: [:index, :unflag]

	def index

		@reports = Report.all

		# @reports.each do |report|
		# 	report.count = 0
		# end
		add = Report.first
		@reports.each do |report|
			add = Report.where(comment_id: report.comment_id)
		end
		if !add.nil?
			add.each {|a| a.count += 1; a.save}
		end

		 @reports.sort_by {|report| report.count}
	end

	def new
		@flag = Report.new
	end

	def create
		@flag = Report.new(report_params)
		if @flag.save
			flash[:success] = "Report successful"
			redirect_to :back
		else
			flash[:danger] = "Report did not work. Please email us for support."
			redirect_to :back
		end
	end

	def destroy
		#@comment = Comment.find(unflag_params[:comment_id])
		@flags = Report.where(comment_id: unflag_params[:comment_id])
		@flags.each {|flag| flag.destroy}
		#@comment.destroy
		redirect_to :back
	end

	def unflag 
		@flags = Report.where(comment_id: unflag_params[:comment_id])
		@flags.each {|f| f.destroy}
		redirect_to reports_path 
	end

	private

		def report_params
			params.require(:report).permit(:user_id, :comment_id, :blog_id, :upload_id, :video_id)
		end

		def unflag_params
			params.require(:report).permit(:comment_id)
		end

		def require_admin
			if !logged_in? or !current_user.admin?
				flash[:danger] = "You must be an administrator to do that."
				redirect_to root_path
			end
		end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<div class="container">
	<div class="row good-background">
		<% if !@reports.nil? && !@reports.empty? %>
			<div align="center">
				<h1>Flags in que: <%= @reports.count %></h1>
			</div>
			<% @reports.each do |report| %>
				<div class="col-sm-3 fix-link flag-list clearfix">
					<% if !report.blog_id.nil? %>
						<%= link_to "Comment #{report.comment_id}, blog #{report.blog_id}", "/blogs/#{report.blog_id}/##{report.comment_id}" %>
					<% elsif !report.upload_id.nil? %>
						<%= link_to "Comment #{report.comment_id}, upload #{report.upload_id}", "/uploads/#{report.upload_id}/##{report.comment_id}" %>
					<% elsif !report.video_id.nil? %>
						<%= link_to "Comment #{report.comment_id}, video #{report.video_id}", "/videos/#{report.video_id}/##{report.comment_id}" %>
					<% end %> <br/>
					<% user = Comment.find(report.comment_id).user_id %>
					<% baduser = User.find(user) %>
					<%= link_to "Bad User: #{baduser.username}, Warn Level: #{baduser.warn_level}", user_path(user) %> <br/>

					<!-- Report count: <%# report.count %> <br/> -->
					Reported by: <%= User.find(report.user_id).username %> <br/>
					<% comment = Comment.find(report.comment_id) %>
					<h4><%= comment.title %></h4>
					<%= truncate(simple_format(comment.comment) , length: 250, escape: false)%> <br/> 
					<div class="row">
						<div class="col-sm-6">
							<%= form_for :report, url: unflag_path do |f| %>
								<%= f.hidden_field :comment_id, value: report.comment_id %>
								<%= f.submit "Unflag", class: "btn btn-sm btn-primary", data: {confirm: "Unflag this comment?"} %>
							<% end %>
						</div>
						<div class="col-sm-6">
							<%= link_to "Delete", comment_path(comment), class: "btn btn-sm btn-warning", method: :delete, data: {confirm: "Delete this comment and warn the user?"} %>
						</div>
					</div>
				</div>
			<% end %>
		<% else %>
			<div align="center" class="move-bottom">
				<h1>Comment sections are peaceful!</h1>
			</div>
		<% end %>
	</div>
</div>